### ISSUE TITLE
Implemenet a delayed shutdown of storage

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-storage#629]
### Description

We can occationally see a few errors and request related issues when we're deploying a new version of Storage. One possible cause is that Storage shuts downs too quickly while requests are still being sent to the k8 pod in question.

We want to mitigate this by delaying the shutdown with a configurable amount of time. 

This addition should primarily mitigate mechanisms in kubernetes as described by the article linked below. Shutdown should not wait for long running GET requests.

### Additional Information

This is an informative article that can be used for inspiration:
https://github.com/dotnet/dotnet-docker/blob/main/samples/kubernetes/graceful-shutdown/graceful-shutdown.md

### Tasks

- [ ] Add a delay to the shutdown of Storage

### Acceptance Criterias

- [ ] Storage waits x number of seconds before terminating.

**Comment by martinothamar** [comment]
This work was done as a preparatory PR before zero-downtime migration from `DaemonSet` -> `Deployment`.

On the C#-side we initially implemented custom `IHostLifetime` here: https://github.com/Altinn/altinn-storage/pull/1011
then later extended the timeout in https://github.com/Altinn/altinn-storage/pull/1019 (since some requests may be slow)

Here is a stripped down manifest showing the various important bits (see inline comments):

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: altinn-storage
  namespace: default
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        azure.workload.identity/skip-containers: linkerd-proxy;linkerd-init
        # Gets converted into preStop config below
        config.alpha.linkerd.io/proxy-wait-before-exit-seconds: "5"
        # Gets converted into LINKERD2_PROXY_SHUTDOWN_GRACE_PERIOD which is handled internally in linkerd2-proxy, see below
        config.linkerd.io/shutdown-grace-period: 50s
        config.linkerd.io/skip-outbound-ports: "443"
        linkerd.io/inject: enabled
    spec:
      # ...
      # Time for container to process SIGTERM, before it is forcefully killed by kubelet
      terminationGracePeriodSeconds: 60
---
# Deployment above results in a Pod like below:
apiVersion: v1
kind: Pod
metadata:
  annotations:
    azure.workload.identity/skip-containers: linkerd-proxy;linkerd-init
    config.alpha.linkerd.io/proxy-wait-before-exit-seconds: "5"
    config.linkerd.io/shutdown-grace-period: 50s
    config.linkerd.io/skip-outbound-ports: "443"
    linkerd.io/inject: enabled
  name: altinn-storage-5ffd9bfb94-vf5gn
  namespace: default
spec:
  containers:
  - env:
    # Handled by linkerd to serve as request drain timeout
    # See https://github.com/linkerd/linkerd2-proxy/blob/8da700cc84483d10066cd8411773140509aad069/linkerd2-proxy/src/main.rs#L124
    - name: LINKERD2_PROXY_SHUTDOWN_GRACE_PERIOD
      value: 50000ms
    lifecycle:
      preStop:
        exec:
          # This delays stop/SIGTERM from being delivered to container
          # which makes this a similar mechanism to custom IHostLifetime + signal handlers + Task.Delay
          command:
          - /bin/sleep
          - "5"
    name: linkerd-proxy
  # storage container...
  terminationGracePeriodSeconds: 60
```

This was tested with a k6 load test script that ran during rollouts (e.g. `kubectl rollout restart` or `r` in k9s).

This config makes both the storage container and linkerd container wait 5s before handling SIGTERM, allowing svc/endpoints/endpoints slice to update first in the normal case. Then both ASP.NET Core and linkerd2-proxy use the same 50s timeout before aborting any remaining active requests
